version: '3.7'
services:
  app:
    build:
      context: ./TextMaker.app
    ports:
      - "5051:443"
    volumes:
      - ./data/certs:/etc/nginx/certs
    depends_on:
      - api
  api:
    build:
      context: ./TextMaker.api